spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
server:
  tomcat:
    max-swallow-size: -1
